import type { Metadata } from "next";
import { Oswald, Lato, Bai_Jamjuree } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/footer";
import LoadingWrapper from "@/components/ui/loader-wrapper";

// import { Oswald, Lato } from "next/font/google";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify available weights
  variable: "--font-oswald",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Specify available weights
  variable: "--font-lato",
});

const bai_jamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Specify available weights
  variable: "--font-bai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
      <body className={`${oswald.variable} ${lato.variable} ${bai_jamjuree.variable} antialiased`}>
        <LoadingWrapper>
          {children}
        </LoadingWrapper>
      </body>
      <Footer />
    </html>
    </>
    
  );
}
